image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"

stages:
  - build
  - test
  - lint
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose run --rm socmedapi sh -c "python manage.py test"

lint:
  stage: lint
  script:
    - docker-compose run --rm socmedapi sh -c "flake8"
    - docker-compose down

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - master