image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"
  POSTGRES_DB: devdb
  POSTGRES_USER: devuser
  POSTGRES_PASSWORD: dbpass
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test
  - lint
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up
    - docker-compose run --rm socmedapi sh -c "/scripts/wait-for-it.sh db:5432 -- python manage.py test"

lint:
  stage: lint
  script:
    - docker-compose run --rm socmedapi sh -c "flake8"
    - docker-compose down

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main