services:
  socmedapi:
    container_name: socmedapi
    build:
      context: .
      args:
        - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./socmedapi:/socmedapi
      - dev-static-data:/vol/web
    command:
      sh -c "python manage.py runserver 0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=dbpass
      - SECRET_KEY=090980809089089x9f0dsaf9
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command:
      sh -c "/myvenv/bin/celery -A socmedapi worker --loglevel=info"
    volumes:
      - ./socmedapi:/socmedapi
    environment:
      - SECRET_KEY=090980809089089x9f0dsaf9
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:15-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=dbpass

  redis:
    container_name: redis
    image: redis:7.0.15-alpine

volumes:
  dev-db-data:
  dev-static-data: